geometry_msgs/Pose2D[] points_to_check    # array of points which should be checked for accessibility
bool approach_path_accessibility_check    # if true, the path to a goal position must be accessible as well
---
bool[] accessibility_flags    			  # array of booleans which correspond to the points and define accessibility (true=free, false=obstacle)